# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-12 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('vpq', models.IntegerField(default=0)),
                ('pos', models.IntegerField(default=0)),
                ('Sz', models.FloatField(default=0)),
                ('Oz', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(verbose_name='Time Stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Acm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('vid', models.IntegerField(default=0)),
                ('pos', models.IntegerField(default=0)),
                ('X', models.FloatField(default=0)),
                ('Y', models.FloatField(default=0)),
                ('Z', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(verbose_name='Time Stamp')),
            ],
        ),
    ]
