# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-25 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accmeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('vid', models.IntegerField(default=0)),
                ('X', models.FloatField(default=0)),
                ('Y', models.FloatField(default=0)),
                ('Z', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(verbose_name='Time Stamp')),
            ],
        ),
    ]
