# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-25 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelo', '0002_accmeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('vid', models.IntegerField(default=0)),
                ('Sx', models.FloatField(default=1)),
                ('Sy', models.FloatField(default=1)),
                ('Sz', models.FloatField(default=1)),
                ('Oy', models.FloatField(default=0)),
                ('Oz', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(verbose_name='Time Stamp')),
            ],
        ),
    ]
