# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-26 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelo', '0003_calibrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrat',
            name='Ox',
            field=models.FloatField(default=0),
        ),
    ]
